Update msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -46,9 +46,17 @@ jobs:
       # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
       run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
 
-    - name: Run the test executable
+    - name: Run the test executable and check for failures
       working-directory: ${{env.GITHUB_WORKSPACE}}
-      run: ./${{env.TEST_EXECUTABLE_PATH}}
+      shell: bash
+      run: |
+        output=$(./MTDS_LW_1-2/x64/Release/MTDS_test.exe)
+        echo "$output"
+        if echo "$output" | grep -q "\[  FAILED  \]"; then
+          echo "One or more tests failed."
+          exit 1
+        fi
+
 
 
 
